#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter '/afs/cern.ch/user/s/scodella/work/BTagging/CMSSW_9_2_11/src/RecoBTag/PerformanceMeasurements/test/Trigger/runTriggerAnalysis.sh /afs/cern.ch/user/s/scodella/work/BTagging/CMSSW_9_2_11/src/RecoBTag/PerformanceMeasurements/test/Trigger JetHT 2016 E,F,G,H'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
