/********************************************************************
* fitterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error fitterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefitterDict();
extern void G__cpp_setup_inheritancefitterDict();
extern void G__cpp_setup_typetablefitterDict();
extern void G__cpp_setup_memvarfitterDict();
extern void G__cpp_setup_globalfitterDict();
extern void G__cpp_setup_memfuncfitterDict();
extern void G__cpp_setup_funcfitterDict();
extern void G__set_cpp_environmentfitterDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "fitter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__fitterDictLN_TClass;
extern G__linked_taginfo G__fitterDictLN_TBuffer;
extern G__linked_taginfo G__fitterDictLN_TMemberInspector;
extern G__linked_taginfo G__fitterDictLN_TObject;
extern G__linked_taginfo G__fitterDictLN_basic_fstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__fitterDictLN_TObjArray;
extern G__linked_taginfo G__fitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__fitterDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__fitterDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__fitterDictLN_TFile;
extern G__linked_taginfo G__fitterDictLN_multimaplEvoidmUcOshortcOlesslEvoidmUgRcOallocatorlEpairlEvoidmUsPconstcOshortgRsPgRsPgR;
extern G__linked_taginfo G__fitterDictLN_TH1;
extern G__linked_taginfo G__fitterDictLN_TCut;
extern G__linked_taginfo G__fitterDictLN_TF1;
extern G__linked_taginfo G__fitterDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__fitterDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__fitterDictLN_TH1F;
extern G__linked_taginfo G__fitterDictLN_TCanvas;
extern G__linked_taginfo G__fitterDictLN_TGraphErrors;
extern G__linked_taginfo G__fitterDictLN_TLatex;
extern G__linked_taginfo G__fitterDictLN_fitter;
extern G__linked_taginfo G__fitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__fitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
