# make file to compile analysis macros
ROOTLIBS      = $(shell root-config --libs)
ROOTGLIBS     = $(shell root-config --glibs)

LIBS          = -L../../src -lBTagEvent $(ROOTLIBS)
GLIBS         = $(ROOTGLIBS) -L/usr/X11R6/lib -lXext -lX11

CXX           = g++

CXXFLAGS      = -fPIC -Wall -Wno-deprecated -m32 -DNOSCRAMV
LDFLAGS       = -fPIC -Wl -m32

LD_LIBRARY_PATH:= $(ROOTSYS)/lib/:$(LD_LIBRARY_PATH)

INCLUDEDIR    = -I$(ROOTSYS)/include -I../../interface -I.

HEADERS       = S8bPerformance.h S8Plotter.h
OBJS          = S8Plotter.o S8PlotterDict.o

all:	$(OBJS)
	$(CXX) -dynamiclib -o libS8Tools.dylib $(LDFLAGS) $(OBJS) $(LIBS)
	@cp libS8Tools.dylib libS8Tools.so

%.o: %.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@ $(INCLUDEDIR)

%Dict.cc: %LinkDef.h
	@echo "Generating dictionary $@"
	@rootcint -f $@ -c -I../../interface -DNOSCRAMV $(HEADERS) $^

clean:
	@rm -f $(OBJS) core *~ *.o *.so 

