common = {
	# 'groups' : ['EventInfo','PV','TagVar','JetInfo','JetSV','JetTrack','CSVTagVar','PFElectron','PFMuon','JetDeepCSV','PatMuon','PatElec','JetDeepFlavour'],
	'groups' : ['EventInfo','PV',
                'PFMuon',"PFElectron",
                'PatMuon','PatElec',
                'TagVar','JetTrack',
                'JetInfo','JetSV','CSVTagVar','JetDeepCSV','JetDeepFlavour','CSVTagTrackVar', 'DeepFlavourFeat',],
	'eras' : ['Run3'],
	'miniAOD' : True,
	'usePuppi' : False,
	'usePuppiForFatJets' : True,
	'usePuppiForBTagging' : False,
	# 'mcGlobalTag' : '112X_mcRun3_2021_realistic_v14',
	'mcGlobalTag' : 'auto:phase1_2021_realistic',
	'remakeAllDiscr' : True,
	'maxJetEta' : 2.5,
	'usePrivateJEC' : False,
	# 'jecDBFileMC' : 'PhaseIIFall17_V5b_MC',
	'inputFiles' : ['/store/relval/CMSSW_11_2_0_pre3/RelValTTbar_14TeV/MINIAODSIM/PU_112X_mcRun3_2021_realistic_v5-v1/20000/4E6AF0AE-EB8E-8847-9C29-5F754974E924.root',],
    # 'JPCalibration' : 'JPcalib_MC81X_v0',
}
